[versions]
# kotlin
stdlib = "2.2.10"
kotlinx-serialization = "1.9.0"

# google deps
guava = "33.4.8-jre"

# utils
lombok = "1.18.36"
annotations = "26.0.2"

# network
jedis = "6.1.0"
hikariCP = "7.0.2"
mariadb = "3.5.5"
exposed = "1.0.0-beta-5"
jedisWrapper = "1.1.4"

#logging
slf4j = "2.1.0-alpha1"
logback = "1.5.18"

# configuration
gson = "2.13.1"
json = "20250517"

# console
jline = "3.30.5"
cloud = "2.0.0"

# platforms
paper = "1.21.1-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"

# dependency injection
koin = "4.1.0"

# config

night-config = "3.8.3"

# shadowJar
shadow = "8.1.1"

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
# kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "stdlib" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization"}

# google libs
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# network
jedis = {group = "redis.clients", name = "jedis", version.ref = "jedis"}
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP" }
mariadb-java-client = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
jedisWrapper = { group = "de.vulpescloud", name = "JedisWrapper", version.ref = "jedisWrapper"}

# logging
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logbackCore = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# configuration
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
json = { group = "org.json", name = "json", version.ref = "json"}

# console
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
cloud = { group = "org.incendo", name = "cloud-core", version.ref = "cloud"}
cloud-extension = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud" }
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud"}
cloud-kotlin-coroutines = { group = "org.incendo", name = "cloud-kotlin-coroutines", version.ref = "cloud"}
cloud-kotlin-coroutines-annotations = { group = "org.incendo", name = "cloud-kotlin-coroutines-annotations", version.ref = "cloud"}
cloud-velocity = { group = "org.incendo", name = "cloud-velocity", version = "2.0.0-SNAPSHOT"}
cloud-processors-confirmation = { group = "org.incendo", name = "cloud-processors-confirmation", version = "1.0.0-rc.1"}

# platforms
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# depdendency injection
koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin"}

# config

nightConfig-toml = { group = "com.electronwill.night-config", name = "toml", version.ref = "night-config" }
nightConfig-json = { group = "com.electronwill.night-config", name = "json", version.ref = "night-config" }
nightConfig-yaml = { group = "com.electronwill.night-config", name = "yaml", version.ref = "night-config" }
