package de.vulpescloud.api.network.redis

enum class RedisHashNames {

    VULPESCLOUD_HEARTBEAT,
    VULPESCLOUD_NODES,
    VULPESCLOUD_SERVICES,
    VULPESCLOUD_TASKS,
    VULPESCLOUD_PLAYERS,
    VULPESCLOUD_PLAYERS_ONLINE;

}