package de.vulpescloud.api.redis

enum class RedisChannelNames {

    VULPESCLOUD_TASK_CREATE,
    VULPESCLOUD_SERVICE_ACTION,
    VULPESCLOUD_SERVICE_EVENT,
    VULPESCLOUD_SERVICE_REGISTER,
    VULPESCLOUD_SERVICE_UNREGISTER,
    VULPESCLOUD_PLAYER_EVENT,
    VULPESCLOUD_PLAYER_ACTION;

}