name: CloudCompile

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew :VulpesCloud-launcher:shadowJar publishAllPublicationsToVulpesCloudSnapshotsRepository copyFilesForMetaRepo

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Publish updater metadata
        uses: s0/git-publish-subdir-action@develop
        if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/renovate/') }}
        env:
          REPO: git@github.com:VulpesCloud/VulpesCloud-meta.git
          BRANCH: ${{ steps.branch-name.outputs.current_branch }}
          FOLDER: 'build/meta-repo'
#          SQUASH_HISTORY: true
#          SKIP_EMPTY_COMMITS: true
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Update Meta for branch {target-branch} of commit {sha}'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VulpesCloud
          path: VulpesCloud-launcher/build/libs/vulpescloud-launcher.jar
